include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_init_to_null
    - await_only_futures
    - cancel_subscriptions
    - camel_case_types
    - close_sinks
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_statements
    - non_constant_identifier_names
    - prefer_is_not_empty

analyzer:
  errors:
    missing_required_param: warning
