include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_void_async
    - await_only_futures
    - cancel_subscriptions
    - camel_case_types
    - close_sinks
    - constant_identifier_names
    - non_constant_identifier_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_catches
    - empty_statements
    - file_names
    - implementation_imports
    - prefer_is_not_empty
    - one_member_abstracts
    - prefer_contains
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_empty
    - unawaited_futures
    - unnecessary_const
    - unnecessary_getters_setters
    - void_checks
    - use_string_buffers
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - unnecessary_parenthesis
    - unnecessary_overrides
    - unnecessary_null_aware_assignments
    - sort_child_properties_last
    - slash_for_doc_comments
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - use_to_and_as_if_applicable
    - sort_pub_dependencies
    - prefer_spread_collections
    - join_return_with_assignment
    - flutter_style_todos
    - avoid_returning_null
    - always_require_non_null_named_parameters
    - always_put_required_named_parameters_first
    - cascade_invocations
    - directives_ordering
    - null_closures
    - library_prefixes
    - no_adjacent_strings_in_list
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - prefer_equal_for_default_values
    - no_duplicate_case_values
    - unrelated_type_equality_checks
    - unnecessary_statements
    - prefer_void_to_null
    - type_init_formals
    - recursive_getters
    - prefer_typing_uninitialized_variables
    - avoid_implementing_value_types
    - prefer_const_literals_to_create_immutables
    - package_names
    - use_function_type_syntax_for_parameters
    - prefer_adjacent_string_concatenation

analyzer:
  errors:
    missing_required_param: warning
