include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_void_async
    - await_only_futures
    - cancel_subscriptions
    - camel_case_types
    - close_sinks
    - constant_identifier_names
    - non_constant_identifier_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_catches
    - empty_statements
    - file_names
    - implementation_imports
    - prefer_is_not_empty
    - one_member_abstracts
    - overridden_fields
    - prefer_contains
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_empty
    - unawaited_futures
    - unnecessary_const
    - unnecessary_getters_setters
    - void_checks
    - use_string_buffers
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - unnecessary_parenthesis
    - unnecessary_overrides
    - unnecessary_null_aware_assignments
    - sort_child_properties_last
    - slash_for_doc_comments

analyzer:
  errors:
    missing_required_param: warning
