include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_void_async
    - await_only_futures
    - cancel_subscriptions
    - camel_case_types
    - close_sinks
    - constant_identifier_names
    - non_constant_identifier_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_catches
    - empty_statements
    - file_names
    - implementation_imports
    - prefer_is_not_empty
    - one_member_abstracts
    - overridden_fields
    - prefer_contains
    - prefer_foreach

analyzer:
  errors:
    missing_required_param: warning
