name: citizen_lab
description: Citizen Lab

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  test: any

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  path_provider: ^1.1.2
  image_picker: ^0.6.0+15
  share: ^0.6.1+1
  shared_preferences: ^0.5.3+2
  url_launcher: ^5.0.5
  sqflite: ^1.1.6+1
  photo_view: ^0.4.2
  csv: ^4.0.3
  sensors: ^0.4.0+1
  provider: ^3.0.0+1
  geolocator: ^5.0.1
  location: ^2.3.5
  local_auth: ^0.5.2+3
  file_picker: ^1.3.7
  webview_flutter: ^0.3.13
  rxdart: ^0.22.0
  pdf: ^1.3.14
  esys_flutter_share: ^1.0.2
  flutter_sound: ^1.4.3
  permission: ^0.1.2
  uuid: ^2.0.2
  logger: ^0.7.0+2

dev_dependencies:
  #pedantic: ^1.7.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/i18n/en.json
   - assets/i18n/de.json 
   - assets/images/aquaponik_anlage.jpg
   - assets/images/autarkes_hochbeet.jpg
   - assets/images/baumscheiben.jpg
   - assets/images/beerengarten_in_koenigshardt.jpg
   - assets/images/beerengarten_in_sterkrade.jpg
   - assets/images/speisepilzgarten.jpg
   - assets/images/aquaponik_am_institut.jpg
   - assets/images/aquaponik_anlage.jpg
   - assets/images/hochbeet.jpg
   - assets/images/stadtgärtnern_oberhausen.jpg
   - assets/images/hochbeet2.jpg
   - assets/images/home_1.jpg
   - assets/images/home_2.jpg
   - assets/ic_launcher.png
   - assets/app_logo.png
   - assets/images/background.jpg
   - assets/images/background_2.jpg
   - assets/images/background_3.jpg
   - assets/images/background_4.jpg
   - assets/images/background6.jpg
   - assets/images/notes_1.jpg
   - assets/images/notes_2.jpg
   - assets/images/notes_3.jpg
   - assets/images/notes_4.jpg
   - assets/images/library.jpg
   - assets/images/mushroom.jpg
   - assets/images/sain_background_1.png
   - assets/images/sain_background_2.png
   - assets/ok.flr

  fonts:
    - family: comparison
      fonts:
        - asset: assets/fonts/ic_comparison.ttf
